# -*- coding: utf-8 -*-
"""HW3_q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDTkMhaCddS68H8ar9-VMnJ5dccA_wQo

## dim=2
"""

import torch
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.nn.functional as functional
import matplotlib.pyplot as plt
import numpy as np
from skimage.metrics import structural_similarity as ssim
import skimage.metrics
import warnings
warnings.filterwarnings("ignore")

class VAE(nn.Module):
    def __init__(self, latent_dim=2, num_classes=10):
        super(VAE, self).__init__()
        self.latent_dim = latent_dim
        self.num_classes = num_classes

        # Encoder
        self.encoder = nn.Sequential(
            nn.Conv2d(1, 16, 3, stride=2, padding=1),
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.Conv2d(16, 32, 3, stride=2, padding=1),
            nn.ReLU(),
            nn.BatchNorm2d(32),
            nn.Conv2d(32, 64, 7),
            nn.ReLU(),
            nn.BatchNorm2d(64),
            nn.Flatten()
        )
        self.fc_mu = nn.Linear(64 + num_classes, latent_dim)
        self.fc_logvar = nn.Linear(64 + num_classes, latent_dim)

        # Decoder
        self.decoder_input = nn.Linear(latent_dim, 64)
        self.decoder = nn.Sequential(
            nn.ConvTranspose2d(64, 32, 7),
            nn.ReLU(),
            nn.BatchNorm2d(32),
            nn.ConvTranspose2d(32, 16, 3, stride=2, padding=1, output_padding=1),  # 16, 14, 14
            nn.ReLU(),
            nn.BatchNorm2d(16),
            nn.ConvTranspose2d(16, 1, 3, stride=2, padding=1, output_padding=1),  # 1, 28, 28
            nn.Sigmoid()
        )

    def sample(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        e = torch.randn_like(std)
        return mu + std * e

    def forward(self, x, labels):
        x = self.encoder(x)
        x = torch.cat((x, labels), dim=1)
        mu = self.fc_mu(x)
        logvar = self.fc_logvar(x)
        z = self.sample(mu, logvar)
        z = self.decoder_input(z).view(-1, 64, 1, 1)
        recon_x = self.decoder(z)
        return recon_x, mu, logvar

def loss_fn(recon_x, x, mu, logvar):
    reconstruction_loss = functional.mse_loss(recon_x, x, reduction="sum")
    kl_div = -0.5 * torch.sum(1 + logvar - mu.pow(2) - logvar.exp())
    return reconstruction_loss + kl_div

def psnr(img1, img2):
    img1 = img1.cpu().numpy().transpose((1, 2, 0))
    img2 = img2.cpu().numpy().transpose((1, 2, 0))
    return skimage.metrics.peak_signal_noise_ratio(img1, img2)

def mse(img1, img2):
    img1 = img1.view(-1)
    img2 = img2.view(-1)
    return torch.mean((img1 - img2) ** 2).item()

def calculate_ssim(img1, img2):
    img1 = img1.cpu().numpy().squeeze()  # Remove channel dimension if it's grayscale
    img2 = img2.cpu().numpy().squeeze()
    return ssim(img1, img2, data_range=img1.max() - img1.min())

transform = transforms.ToTensor()
dataset = datasets.MNIST(root="data", download=True, transform=transform)
batch_size = 128
train_dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=0)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

latent_dim = 2
model = VAE(latent_dim=latent_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 50

# Training loop
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for images, labels in train_dataloader:
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)
        loss = loss_fn(recon_x, images, mu, logvar)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {running_loss/len(train_dataloader.dataset):.4f}")

model.eval()
with torch.no_grad():
    for idx, (images, labels) in enumerate(train_dataloader):
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)

        original_image = images[1]
        reconstructed_image = recon_x[1]

        psnr_value = psnr(original_image, reconstructed_image)
        mse_value = mse(original_image, reconstructed_image)

        ssim_value = calculate_ssim(original_image, reconstructed_image)

        print(f"PSNR: {psnr_value:.2f}, MSE: {mse_value:.6f}, SSIM: {ssim_value:.4f}")

        fig = plt.figure(figsize=(8, 4))
        fig.add_subplot(1, 2, 1)
        original_image = original_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Original Image")
        plt.imshow(original_image)

        fig.add_subplot(1, 2, 2)
        reconstructed_image = reconstructed_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Reconstructed Image")
        plt.imshow(reconstructed_image)

        plt.show()
        break

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as functional

def extract_latent_features_limited(model, dataloader, device, num_samples):
    model.eval()
    latent_features = []
    labels_list = []
    samples_processed = 0

    with torch.no_grad():
        for images, labels in dataloader:
            if samples_processed >= num_samples:
                break

            images = images.to(device)
            labels = labels.to(device)
            labels_onehot = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
            _, mu, _ = model(images, labels_onehot)
            latent_features.append(mu.cpu().numpy())
            labels_list.append(labels.cpu().numpy())

            samples_processed += len(images)

    latent_features = np.concatenate(latent_features, axis=0)
    labels_list = np.concatenate(labels_list, axis=0)

    return latent_features, labels_list

num_samples = 6000
latent_features, labels = extract_latent_features_limited(model, train_dataloader, device, num_samples)

plt.figure(figsize=(10, 8))
unique_labels = np.unique(labels)
for label in unique_labels:
    indices = labels == label
    plt.scatter(latent_features[indices, 0], latent_features[indices, 1], label=f"Label {label}", s=10)

plt.title("2D Latent Space of MNIST VAE")
plt.xlabel("Latent Dimension 1")
plt.ylabel("Latent Dimension 2")
plt.legend()
plt.show()

"""## dim=4"""

latent_dim = 4
model = VAE(latent_dim=latent_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 50

# Training loop
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for images, labels in train_dataloader:
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)
        loss = loss_fn(recon_x, images, mu, logvar)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {running_loss/len(train_dataloader.dataset):.4f}")

model.eval()
with torch.no_grad():
    for idx, (images, labels) in enumerate(train_dataloader):
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)

        original_image = images[1]
        reconstructed_image = recon_x[1]

        psnr_value = psnr(original_image, reconstructed_image)
        mse_value = mse(original_image, reconstructed_image)
        ssim_value = calculate_ssim(original_image, reconstructed_image)

        print(f"PSNR: {psnr_value:.2f}, MSE: {mse_value:.6f}, SSIM: {ssim_value:.4f}")

        fig = plt.figure(figsize=(8, 4))
        fig.add_subplot(1, 2, 1)
        original_image = original_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Original Image")
        plt.imshow(original_image)

        fig.add_subplot(1, 2, 2)
        reconstructed_image = reconstructed_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Reconstructed Image")
        plt.imshow(reconstructed_image)

        plt.show()
        break

import torch
import torch.nn.functional as functional
from sklearn.manifold import TSNE


num_samples = 6000
latent_features, labels = extract_latent_features_limited(model, train_dataloader, device, num_samples)

tsne = TSNE(n_components=2, random_state=42)
latent_2d = tsne.fit_transform(latent_features)

plt.figure(figsize=(10, 8))
unique_labels = np.unique(labels)
for label in unique_labels:
    indices = labels == label
    plt.scatter(latent_2d[indices, 0], latent_2d[indices, 1], label=f"Label {label}", s=10)

plt.title("2D Latent Space of MNIST VAE (t-SNE Reduced from 4D)")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend()
plt.show()

""" ## dim=16"""

latent_dim = 16
model = VAE(latent_dim=latent_dim).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
epochs = 50

# Training loop
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for images, labels in train_dataloader:
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)
        loss = loss_fn(recon_x, images, mu, logvar)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {running_loss/len(train_dataloader.dataset):.4f}")

model.eval()
with torch.no_grad():
    for idx, (images, labels) in enumerate(train_dataloader):
        images = images.to(device)
        labels = functional.one_hot(labels, num_classes=10).float().to(device)  # Convert labels to one-hot
        recon_x, mu, logvar = model(images, labels)

        original_image = images[1]
        reconstructed_image = recon_x[1]

        psnr_value = psnr(original_image, reconstructed_image)
        mse_value = mse(original_image, reconstructed_image)
        ssim_value = calculate_ssim(original_image, reconstructed_image)

        print(f"PSNR: {psnr_value:.2f}, MSE: {mse_value:.6f}, SSIM: {ssim_value:.4f}")

        fig = plt.figure(figsize=(8, 4))
        fig.add_subplot(1, 2, 1)
        original_image = original_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Original Image")
        plt.imshow(original_image)

        fig.add_subplot(1, 2, 2)
        reconstructed_image = reconstructed_image.cpu().numpy().transpose((1, 2, 0))
        plt.title("Reconstructed Image")
        plt.imshow(reconstructed_image)

        plt.show()
        break

num_samples = 6000
latent_features, labels = extract_latent_features_limited(model, train_dataloader, device, num_samples)

tsne = TSNE(n_components=2, random_state=42)
latent_2d = tsne.fit_transform(latent_features)

plt.figure(figsize=(10, 8))
unique_labels = np.unique(labels)
for label in unique_labels:
    indices = labels == label
    plt.scatter(latent_2d[indices, 0], latent_2d[indices, 1], label=f"Label {label}", s=10)

plt.title("2D Latent Space of MNIST VAE (t-SNE Reduced from 4D)")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.legend()
plt.show()